In [1]:
import numpy as np

In [2]:
np.sum?

In [3]:
x=np.array(1)

In [6]:
x=np.array([[[1,2,3],[4,5,6]],[[1,0,3],[5,6,9]]])

In [10]:
print(x.shape)
print(x.ndim)
print(x)

(2, 2, 3)
3
[[[1 2 3]
  [4 5 6]]

 [[1 0 3]
  [5 6 9]]]


In [14]:
x[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
x[0][1]

array([4, 5, 6])

In [16]:
x[0][1][1]

5

In [18]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [19]:
np.zeros_like(x)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [20]:
np.ones_like(x)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [29]:
a=np.random.random((10,10))
a

array([[ 0.68597781,  0.68892773,  0.95331621,  0.84321379,  0.64552298,
         0.66336037,  0.65661561,  0.94233883,  0.05188663,  0.80664376],
       [ 0.86886281,  0.98387754,  0.2758502 ,  0.67139791,  0.63917027,
         0.04098773,  0.85862916,  0.30039   ,  0.84698224,  0.50023152],
       [ 0.27190977,  0.23806335,  0.97047431,  0.12456767,  0.45657619,
         0.11206153,  0.52417954,  0.17472003,  0.14858425,  0.03392288],
       [ 0.91951109,  0.85407181,  0.16637935,  0.52540201,  0.42137032,
         0.37469878,  0.99166988,  0.6081506 ,  0.48403557,  0.5030363 ],
       [ 0.23061432,  0.89838393,  0.65480516,  0.27063185,  0.42994925,
         0.02315802,  0.33492986,  0.57684332,  0.80194073,  0.29885454],
       [ 0.24543401,  0.29231697,  0.90390999,  0.69436448,  0.03291237,
         0.34777512,  0.54081903,  0.03007564,  0.92832039,  0.47269444],
       [ 0.74793376,  0.83961995,  0.21816604,  0.21970736,  0.57904129,
         0.85223253,  0.30436733,  0.72248796

In [30]:
a[-1,-1]

0.79069627388399277

In [32]:
x=np.array([1,2,3])
y=np.array([[1,2,3],[4,5,6]])

In [33]:
x+y

array([[2, 4, 6],
       [5, 7, 9]])

In [34]:
import pandas as pd